#!/usr/bin/env python3
"""Regenerates the apps/api env var table in env-vars.md straight from
apps/api/src/gnt/config.py's Settings class, so that table can't drift out
of sync with the real source of truth the way a hand-copied one would.

Parses config.py's AST instead of importing pydantic — the field list, type
annotations, and defaults are all static syntax, and every field's
explanation lives in the plain '#' comment block written directly above it
in the source. No need to construct a real Settings() (which would require
every required env var to already be set) just to read its shape.

Run from anywhere:
    python3 docs/self-hosting/gen_env_vars.py

Rewrites the "## apps/api" table in docs/self-hosting/env-vars.md between
the AUTOGENERATED markers. Everything outside those markers (apps/store's
hand-enumerated table, prose) is left untouched.
"""

import ast
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = REPO_ROOT / "apps/api/src/gnt/config.py"
ENV_VARS_MD = Path(__file__).resolve().parent / "env-vars.md"

START_MARKER = "<!-- AUTOGENERATED:apps-api START (docs/self-hosting/gen_env_vars.py) -->"
END_MARKER = "<!-- AUTOGENERATED:apps-api END -->"


def field_default(node: ast.AST) -> tuple[str, bool]:
    """Returns (default_repr, required). A bare `Field(...)` call is read
    for its `default=` keyword; anything else is unparsed as-is."""
    if isinstance(node, ast.Call) and getattr(node.func, "id", None) == "Field":
        for kw in node.keywords:
            if kw.arg == "default":
                return ast.unparse(kw.value), False
        return "(no default)", True
    return ast.unparse(node), False


def leading_comment(lines: list[str], lineno: int) -> str:
    """Walks upward from the field's own line collecting a contiguous block
    of '#' comment lines directly above it, stops at the first blank or
    non-comment line."""
    out: list[str] = []
    i = lineno - 2  # lineno is 1-indexed; line above the field
    while i >= 0:
        stripped = lines[i].strip()
        if stripped.startswith("#"):
            out.insert(0, stripped.lstrip("#").strip())
            i -= 1
        else:
            break
    return " ".join(out)


NOTE_MAX_CHARS = 160


def summarize(comment: str) -> str:
    """Most of config.py's field comments are multi-paragraph design
    rationale -- accurate, but unreadable stuffed whole into a table cell.
    Truncates to a short lead-in instead of a hand-picked summary, so this
    stays a mechanical transform of the real comment (can't drift) rather
    than editorial content (could)."""
    if len(comment) <= NOTE_MAX_CHARS:
        return comment
    cut = comment[:NOTE_MAX_CHARS].rsplit(" ", 1)[0]
    return f"{cut}…"


def main() -> None:
    source = CONFIG_PATH.read_text()
    lines = source.splitlines()
    tree = ast.parse(source)

    settings_cls = next(
        node for node in ast.walk(tree) if isinstance(node, ast.ClassDef) and node.name == "Settings"
    )

    rows = []
    for stmt in settings_cls.body:
        if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
            continue
        name = stmt.target.id
        type_str = ast.unparse(stmt.annotation)
        if stmt.value is None:
            default, required = "(no default)", True
        else:
            default, required = field_default(stmt.value)
        comment = leading_comment(lines, stmt.lineno)
        rows.append((name.upper(), type_str, "yes" if required else "no", default, comment))

    table_lines = [
        "| Env var | Type | Required | Default | Notes |",
        "|---|---|---|---|---|",
    ]
    for name, type_str, required, default, comment in rows:
        note = summarize(comment).replace("|", "\\|") if comment else ""
        table_lines.append(f"| `{name}` | `{type_str}` | {required} | `{default}` | {note} |")

    table = "\n".join(table_lines)
    generated = f"{START_MARKER}\n{table}\n{END_MARKER}"

    doc = ENV_VARS_MD.read_text()
    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(doc):
        raise SystemExit(f"markers not found in {ENV_VARS_MD} -- add {START_MARKER!r}/{END_MARKER!r} first")
    ENV_VARS_MD.write_text(pattern.sub(generated, doc))
    print(f"wrote {len(rows)} apps/api settings fields into {ENV_VARS_MD}")


if __name__ == "__main__":
    main()
